name: CI/CD Pipeline

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        name: Run Tests
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Run tests
              run: npm test

            - name: Lint code
              run: npm run lint
              continue-on-error: true

    build:
        name: Build Application
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Build frontend
              run: npm run build --workspace=frontend

            - name: Build backend
              run: npm run build --workspace=backend

    # All checks must pass for branch protection
    all-checks-pass:
        name: All Checks Passed
        runs-on: ubuntu-latest
        needs: [test, build]
        if: always()
        steps:
            - name: Verify all jobs passed
              run: |
                if [ "${{ needs.test.result }}" != "success" ] || [ "${{ needs.build.result }}" != "success" ]; then
                  echo "One or more required checks failed"
                  exit 1
                fi
                echo "All required checks passed!"
